version: '3'

services:
 webapi:  
  build: ./WebApi
  ports:
   - "5000:5000"

 mongodb:
  image: mongo
  ports:
   - "27017:27017"

 mongo_seed:
    build:
     context: .
     dockerfile: ./mongo_seed
    links:
      - mongodb    

